### ISSUE TITLE
Unclear usage description

### ISSUE THREAD

**Issue by indigo423** [getgrav/grav-plugin-github#1]
I struggled following the usage instruction. As soon I create a github.md file it tells me 

```
404 - Template "modular/github.html.twig" is not defined.
```

Can you please provide an example directory structure and content how to use the example you've provided?

Thank you in advance.

**Comment by flaviocopes** [comment]
The plugin activates only if `github: true` is found in the page header.

It does not provide a modular, but a partial that you can include in another Twig template: https://github.com/getgrav/grav-plugin-github/tree/develop/templates/partials

For example, add a `github.html.twig` into your theme `templates` folder, and call `{% include 'partials/github.html.twig' %}`.

**Comment by indigo423** [comment]
@flaviocopes I got it to work, thank you for your additional explanation, helped me. Sorry for the noob questions :) 🍺
